name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repo
      - uses: actions/checkout@v4

      # Install Java dan Buildozer
      - name: Install Buildozer & Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel build-essential \
                              git zip unzip openjdk-17-jdk android-sdk adb
          pip install --upgrade pip
          pip install --upgrade buildozer cython

      # Setup Android SDK
      - name: Setup Android SDK & Build Tools
        run: |
          mkdir -p $HOME/android-sdk
          echo "y" | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;21.4.7075529"
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/33.0.2" >> $GITHUB_ENV

      # Grant permission to gradle wrapper (if any)
      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew || true

      # Build APK using Buildozer
      - name: Build APK
        run: |
          buildozer android debug

      # Upload APK hasil build ke GitHub Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
