name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel build-essential \
                              git zip unzip wget openjdk-17-jdk libssl-dev zlib1g-dev
          pip install --upgrade pip
          pip install --upgrade buildozer cython virtualenv

      - name: Setup Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH

      - name: Accept Licenses and Install Packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          sdkmanager --install "ndk;21.4.7075529"

      - name: Initialize Buildozer
        run: |
          buildozer init
          # Force create the android platform directory
          mkdir -p .buildozer/android/platform
          # Update buildozer.spec with correct paths
          sed -i 's|^android.sdk_path = .*|android.sdk_path = /home/runner/android-sdk|' buildozer.spec
          sed -i 's|^android.ndk_path = .*|android.ndk_path = /home/runner/android-sdk/ndk/21.4.7075529|' buildozer.spec
          sed -i 's|^android.p4a_dir = .*|android.p4a_dir = /home/runner/work/_temp/.buildozer/android/platform/python-for-android|' buildozer.spec

      - name: Build APK (with retry)
        run: |
          # First try might fail to download dependencies
          buildozer android clean || true
          # Second try with fresh download
          buildozer android debug
          # Verify APK was created
          ls -la bin/

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
